// Serves private bucket objects at /media/<s3-key>. Content stores these
// app-relative paths, so both <img> and next/image resolve through here.

import { getObjectStream } from '../../../src/lib/storage';

// Keys are generated by uploadMedia (uploads/yyyy/mm/name-hex.ext); anything
// with traversal segments, empty parts or backslashes never came from us.
const sanitiseKey = (segments) => {
  if (!Array.isArray(segments) || segments.length === 0) return null;
  for (const segment of segments) {
    if (!segment || segment === '.' || segment === '..') return null;
    if (segment.includes('\\') || segment.includes('\0')) return null;
  }
  return segments.join('/');
};

const notFound = () => new Response('Not found', { status: 404 });

const objectHeaders = (object) => {
  const headers = new Headers({
    'Content-Type': object.contentType,
    'Cache-Control': 'public, max-age=31536000, immutable',
    'X-Content-Type-Options': 'nosniff',
  });
  if (object.contentLength != null) {
    headers.set('Content-Length', String(object.contentLength));
  }
  return headers;
};

export async function GET(request, { params }) {
  const { key } = await params;
  const cleanKey = sanitiseKey(key);
  if (!cleanKey) return notFound();

  const object = await getObjectStream(cleanKey);
  if (!object) return notFound();

  return new Response(object.body.transformToWebStream(), {
    headers: objectHeaders(object),
  });
}

export async function HEAD(request, { params }) {
  const { key } = await params;
  const cleanKey = sanitiseKey(key);
  if (!cleanKey) return notFound();

  const object = await getObjectStream(cleanKey);
  if (!object) return notFound();

  // GetObject opened a body we will not send; release the connection.
  object.body?.destroy?.();

  return new Response(null, { headers: objectHeaders(object) });
}
